### ISSUE TITLE
thumbnail can't appear

### ISSUE THREAD

**Issue by JasonWu55** [PmzHeroV69/BansWebhook#2]
ban:
  enabled: true
  webhook-url: "Private"
  webhook-title: "封鎖通知"
  webhook-thumbnail: "https://mc-heads.net/avatar/{player}/512"
  webhook-color: "ff0000"
  fields:
    "處理人": "{executor}"
    "違規者": "{player}"
    "原因": "{reason}"
    "封鎖時長": "{duration}"

**Comment by PmzHeroV69** [comment]
Hello, this placeholder is not supported on the thumbnail yet, i will add it in the next update
