### ISSUE TITLE
Add unban/unmute/unwarn webhooks

### ISSUE THREAD

**Issue by SenPr** [PmzHeroV69/BansWebhook#3]
Great plugin for logging/announcing things on Discord!
Thought I would like to also log unban/unmute/unwarn as well.

Greatly appreciated if it is implemented.

**Comment by Mike5357** [comment]
Bump

**Comment by PmzHeroV69** [comment]
Hello. im sorry for the delay i was not able to work on the project. this feature is added in the new version, Thanks for your suggestion :)
